name: CI
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.env.sample'
      - 'README.md'
      - 'infra/**'
      - '.changeset/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.env.sample'
      - 'README.md'
      - 'infra/**'
      - '.changeset/**'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.event.pull_request.head.ref }}

