name: Version
permissions:
  pull-requests: write
  contents: write

on:
  push:
    tags:
      - 'test**.**.**'

# concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checker
        run: echo Ran
